### ISSUE TITLE
Error:java.lang.RuntimeException: java.lang.NullPointerException: element == null

### ISSUE THREAD

**Issue by SunnyTime** [mqzhangw/JIMU#26]
我仿照您的代码，编译报错：Error:java.lang.RuntimeException: java.lang.NullPointerException: element == null；
在messages中看到如下错误信息：
注: [Router-Anno-Compiler]-- >>> AutowiredProcessor init. <<<
注: [Router-Anno-Compiler]-- >>> host is app <<<
注: [Router-Anno-Compiler]-- >>> RouteProcessor init. <<<
注: [Router-Anno-Compiler]-- >>> Found routes, start... <<<
注: [Router-Anno-Compiler]-- >>> Found activity route: com.test.jm.MainActivity <<<
:app:compileDebugJavaWithJavac FAILED
:app:compileDebugJavaWithJavac (Thread[Daemon worker Thread 46,5,main]) completed. Took 0.647 secs.

现在一直无法解决。烦劳大神判断一下什么地方不对！

**Comment by SunnyTime** [comment]
Error:java.lang.RuntimeException: java.lang.NullPointerException: element == null；

**Comment by xinjiuyijiu** [comment]
碰到同样的问题

**Comment by leobert-lan** [comment]
贴一下 com.test.jm.MainActivity.java 完整代码

**Comment by xinjiuyijiu** [comment]
![5 z_guuo3c 83bobor5vt14](https://user-images.githubusercontent.com/17042019/41714940-7e04c808-7584-11e8-91be-8309cd10287b.png)
弄了好久，一直是这个问题，尝试换过gradle和tool.gradle版本，route-compiler版本都没法解决

**Comment by SunnyTime** [comment]
package com.leadbank.jm;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;

import com.alibaba.android.arouter.launcher.ARouter;
import com.leadbank.component.ToastManager;
import com.leadbank.component.componentlib.service.AutowiredService;
import com.luojilab.router.facade.annotation.RouteNode;

//@Route(path = "/test/MainActivity")
@RouteNode(path = "/main", desc = "主页面")
public class MainActivity extends AppCompatActivity implements View.OnClickListener{

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        AutowiredService.Factory.getSingletonImpl().autowire(this);
        setContentView(R.layout.activity_main);
        ToastManager.show(this, "-------");

        findViewById(R.id.ui_router_demos).setOnClickListener(this);
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.ui_router_demos:

                break;
        }
    }
}
由于一直没办法解决所以改用ARouter了，用ARouter注解编译没有问题，但是只要使用@RouteNode注解就会编译报错

报错log如下：
注: [Router-Anno-Compiler]-- >>> AutowiredProcessor init. <<<
注: [Router-Anno-Compiler]-- >>> host is null <<<
注: [Router-Anno-Compiler]-- >>> RouteProcessor init. <<<
注: [Router-Anno-Compiler]-- >>> Found routes, start... <<<
注: [Router-Anno-Compiler]-- >>> Found activity route: com.leadbank.jm.MainActivity <<<

:app:compileDebugJavaWithJavac FAILED
:app:compileDebugJavaWithJavac (Thread[Task worker for ':',5,main]) completed. Took 2.392 secs.
:app:buildInfoGeneratorDebug (Thread[Task worker for ':' Thread 2,5,main]) started.
:app:buildInfoGeneratorDebug
Putting task artifact state for task ':app:buildInfoGeneratorDebug' into context took 0.0 secs.
Executing task ':app:buildInfoGeneratorDebug' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:buildInfoGeneratorDebug (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.037 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NullPointerException: element == null

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: element == null
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:49)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:99)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:198)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:183)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:120)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 30 more
Caused by: java.lang.NullPointerException: element == null
	at com.squareup.javapoet.Util.checkNotNull(Util.java:68)
	at com.squareup.javapoet.ClassName.get(ClassName.java:209)
	at com.luojilab.router.compiler.processor.RouterProcessor.generateRouterImpl(RouterProcessor.java:163)
	at com.luojilab.router.compiler.processor.RouterProcessor.process(RouterProcessor.java:117)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 58 more


* Get more help at https://help.gradle.org

BUILD FAILED in 48s

147 actionable tasks: 4 executed, 143 up-to-date

**Comment by leobert-lan** [comment]
thanks to providing the whole output message.

关键代码：
```
 // superClassName
        ClassName superClass = ClassName.get(elements.getTypeElement(BASECOMPROUTER));
```
意图得到该类：
```
 String BASECOMPROUTER = "com.luojilab.component.componentlib.router.ui.BaseCompRouter";

```

位于componentlib库、该包中：
```
package com.luojilab.component.componentlib.router.ui;
...
public abstract class BaseCompRouter implements IComponentRouter {
...
}
```
请确认以下几点：

- *该Module*是否使用了componentlib依赖，最新的为：`compile 'com.github.jimu:componentlib:1.3.1'`
- 确保版本适配，最新的适配版本套件：
> componentlib:1.3.1
> router-annotation:1.0.1
> router-annotation-compiler:1.0.1;
- 使用的componentlib库中`BaseCompRouter`没有被混淆

**Comment by xinjiuyijiu** [comment]
感谢大大的回复，根据你的提示找到了问题：
在Constant.class下定义了：
    String ISYRINGE = "com.luojilab.component.componentlib.router.ISyringe";

    String JSON_SERVICE = "com.luojilab.component.componentlib.service.JsonService";

    String BASECOMPROUTER = "com.luojilab.component.componentlib.router.ui.BaseCompRouter";
这三个类路径。我是直接下载了demo，然后将componentlib中的内容复制到我的项目中，这样导致修改了这些类的路径，找不到这些类了，很抱歉才看到回复。。。有点迟了
