### ISSUE TITLE
引入rxlifecycle:2.2.2引起的问题

### ISSUE THREAD

**Issue by yefl2064** [mqzhangw/JIMU#46]
在baseLib里面引入了com.trello.rxlifecycle2:rxlifecycle:2.2.2 com.trello.rxlifecycle2:rxlifecycle-components:2.2.2  出现了：  
java.lang.Error: Cleaner terminated abnormally
	at sun.misc.Cleaner$1.run(Cleaner.java:148)
	at sun.misc.Cleaner$1.run(Cleaner.java:145)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.Cleaner.clean(Cleaner.java:145)
	at sun.nio.ch.FileChannelImpl.unmap(FileChannelImpl.java:849)
	at sun.nio.ch.FileChannelImpl.transferFromFileChannel(FileChannelImpl.java:647)
	at sun.nio.ch.FileChannelImpl.transferFrom(FileChannelImpl.java:708)
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1147)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at org.apache.commons.io.FileUtils$copyFile$0.call(Unknown Source)
	at com.dd.buildgradle.ComCodeTransform$_transform_closure3$_closure5.doCall(ComCodeTransform.groovy:79)
	at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
。。。。

Caused by: java.io.IOException: 试图访问无效的地址。
	at sun.nio.ch.FileChannelImpl.unmap0(Native Method)
	at sun.nio.ch.FileChannelImpl.access$000(FileChannelImpl.java:50)
	at sun.nio.ch.FileChannelImpl$Unmapper.run(FileChannelImpl.java:826)
	at sun.misc.Cleaner.clean(Cleaner.java:143)
	... 99 more

**Comment by yefl2064** [comment]
在rxlifecycle 引用时增加 exculde module ‘rxjava’ ，这个错误没有了。
